openapi: 3.0.3
info:
  title: SatBeat
  description: API utilizada para gerar arquivos de exemplo através do VSCode
  version: 0.0.1
servers:
  - url: https://api.server.test/v1
paths:
  /api/sat/beat:
    post:
      summary: Checks system status
      description: Checks system status
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/satBeatRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/satBeatResponse'
        '400':
          description: 400 | Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: 400 | Bad Request
components:
  schemas:
    environment:
      type: string
      title: env
      description: |
        Defines the execution environment:
         - `test`: Development testing environment.
         - `stage`: Pre-production testing environment.
         - `prod`: Production environment.
      enum:
        - test
        - stage
        - prod
      example: test
    version:
      type: string
      title: version
      description: 'Schema of Version of Parameters File, using a major.minor.patch versioning scheme (Ex.: 2.1.3)'
      pattern: ^\d+\.\d+\.\d+$
      example: 2.0.0
    identitySat:
      type: string
      title: SatID
      description: Schema of SAT ID
      minLength: 1
      maxLength: 64
      pattern: ^SAT\d{21}$
      example: SAT12345678900001823
    serialNumber:
      type: string
      title: SAT Serial Number
      format: uuid
      description: Schema of SAT Serial Number, use the format UUIDv4
      minLength: 32
      maxLength: 36
      pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-4[0-9a-fA-F]{3}-[89a-bA-B][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$
      example: FA59BA20-E176-4597-B211-6F5DE7109D7A
    satBeatRequest:
      type: object
      title: satBeatRequest
      description: 'Schema of Initial Parameters file '
      required:
        - env
        - version
        - appID
        - satSN
      properties:
        env:
          $ref: '#/components/schemas/environment'
        version:
          $ref: '#/components/schemas/version'
        appID:
          $ref: '#/components/schemas/identitySat'
        satSN:
          $ref: '#/components/schemas/serialNumber'
    cmd:
      type: boolean
      title: cmd
      description: Schema of command
      example: true
    satBeatResponse:
      type: object
      title: satBeatResponse
      description: 'Schema of Initial Parameters file '
      required:
        - env
        - version
        - appID
        - satSN
        - appCmd
        - satCmd
      properties:
        env:
          $ref: '#/components/schemas/environment'
        version:
          $ref: '#/components/schemas/version'
        appID:
          $ref: '#/components/schemas/identitySat'
        satSN:
          $ref: '#/components/schemas/serialNumber'
        appCmd:
          $ref: '#/components/schemas/cmd'
        satCmd:
          $ref: '#/components/schemas/cmd'
