openapi: 3.0.3
info:
  title: SatHolder
  description: API utilizada para gerar arquivos de exemplo através do VSCode
  version: 0.0.1
servers:
  - url: https://api.server.test/v1
paths:
  /api/sat/holder:
    post:
      summary: Activates the holder
      description: Activates the holder
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/satHolderRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/satHolderResponse'
        '400':
          description: 400 | Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: 400 | Bad Request
components:
  schemas:
    environment:
      type: string
      title: env
      description: |
        Defines the execution environment:
         - `test`: Development testing environment.
         - `stage`: Pre-production testing environment.
         - `prod`: Production environment.
      enum:
        - test
        - stage
        - prod
      example: test
    version:
      type: string
      title: version
      description: 'Schema of Version of Parameters File, using a major.minor.patch versioning scheme (Ex.: 2.1.3)'
      pattern: ^\d+\.\d+\.\d+$
      example: 2.0.0
    identitySat:
      type: string
      title: SatID
      description: Schema of SAT ID
      minLength: 1
      maxLength: 64
      pattern: ^SAT\d{21}$
      example: SAT12345678900001823
    serialNumber:
      type: string
      title: SAT Serial Number
      format: uuid
      description: Schema of SAT Serial Number, use the format UUIDv4
      minLength: 32
      maxLength: 36
      pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-4[0-9a-fA-F]{3}-[89a-bA-B][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$
      example: FA59BA20-E176-4597-B211-6F5DE7109D7A
    accessToken:
      type: string
      title: accessToken
      description: The Access Token
      example: eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCIsImp3ayI6eyJrdHkiOiJFQyIsImNydiI6IlAtMjU2IiwieCI6ImtoM3JIbS1xcDhYN3Exdm1qTl9fZGlualJHRTFvcEdKTjFDX1lsTnNvTUEiLCJ5IjoicG1aS1o1ZFo5eEQ3R0ZYYmVCSmNWUnRwVHZVNjROc0h6YmMtQnRHdFE1VSJ9fQ.eyJkYXRhIjoiZXhlbXBsbyBkZSBkb2N1bWVudG8gSlNPTiJ9.hH_3oZKMyDzbYHIEjCJWgGuKOrTwexrX4SJ-hh1njRvoa2cR8wnATt4rLdpj4ApKQt8unIDBukNOQ3_XkpOPPQ
    activation:
      type: object
      title: activation
      description: Activation holder
      required:
        - ID
        - type
      properties:
        ID:
          type: string
          description: city of Address
          example: '345894759847359'
        type:
          type: string
          description: Street of Address.
          example: CNPJ
    satHolderRequest:
      type: object
      title: satHolderRequest
      description: 'Schema of Initial Parameters file '
      required:
        - env
        - version
        - appID
        - satID
        - satSN
        - accessToken
        - activation
      properties:
        env:
          $ref: '#/components/schemas/environment'
        version:
          $ref: '#/components/schemas/version'
        appID:
          $ref: '#/components/schemas/identitySat'
        satID:
          $ref: '#/components/schemas/identitySat'
        satSN:
          $ref: '#/components/schemas/serialNumber'
        accessToken:
          $ref: '#/components/schemas/accessToken'
        activation:
          $ref: '#/components/schemas/activation'
    cmd:
      type: boolean
      title: cmd
      description: Schema of command
      example: true
    IdentitySat:
      type: string
      title: SatID
      description: Schema of SAT ID
      minLength: 1
      maxLength: 64
      pattern: ^SAT\d{21}$
      example: SAT12345678900001823
    Name:
      type: string
      title: Name
      description: Schema of name
      minLength: 1
      maxLength: 255
      example: Stack holder Teste
    Email:
      type: string
      title: email
      description: email address
      minLength: 1
      maxLength: 255
      format: email
      pattern: ^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$
      example: acme@acme.com
    Phone:
      type: string
      title: phone
      description: Schema of phone
      minLength: 1
      maxLength: 64
      pattern: ^\+(\d{1,3})\s?\(?\d{1,3}\)?\s?\d{4,5}[-\s]?\d{4}$
      example: +55 (11) 91234-1234
    append:
      type: object
      title: append
      description: Schema for Custom Attribute Data
      required:
        - key
        - value
      properties:
        key:
          type: string
          description: The key of the custom attribute.
          minLength: 1
          maxLength: 64
          example: CNPJ
        value:
          type: object
          description: The value of the custom attribute.
          example: '12345678900001'
    Address:
      type: object
      title: Address
      description: Schema of Address
      required:
        - street
        - city
        - stateProvince
        - postalCode
        - country
      properties:
        street:
          type: string
          description: Street of Address.
          example: Avenida Brasil, 1234 - CJ. 123
        city:
          type: string
          description: city of Address
          example: SAO PAULO
        stateProvince:
          type: string
          description: stateProvince of Address
          example: SAO PAULO
        postalCode:
          type: string
          description: postalCode of Address
          pattern: ^\d{5}-?\d{3}$
          example: 07013-678
        country:
          type: string
          description: country of Address, ISO 3166-1 & ISO 3166/MA (alpha-3)
          minLength: 3
          maxLength: 3
          example: BRA
    holders:
      type: object
      title: holders
      description: Schema of HolderContact
      required:
        - holderID
        - holderType
        - name
        - email
        - phone
        - address
        - organization
      properties:
        holderID:
          description: Stackholder ID registry in SAT 2.0.
          $ref: '#/components/schemas/IdentitySat'
        holderType:
          type: string
          title: holderType
          description: Schema of holderType
          minLength: 1
          maxLength: 8
          example: adm
        name:
          description: Name of Stackholder.
          $ref: '#/components/schemas/Name'
        email:
          description: Email of Stackholder Contact.
          $ref: '#/components/schemas/Email'
        phone:
          description: Phone of Stackholder Contact.
          $ref: '#/components/schemas/Phone'
        append:
          type: array
          description: Custom attribute append.
          items:
            $ref: '#/components/schemas/append'
        address:
          description: Address of Stackholder.
          $ref: '#/components/schemas/Address'
    satHolderResponse:
      type: object
      title: satHolderResponse
      description: 'Schema of Initial Parameters file '
      required:
        - env
        - version
        - appID
        - satID
        - satSN
        - appCmd
        - satCmd
        - holders
      properties:
        env:
          $ref: '#/components/schemas/environment'
        version:
          $ref: '#/components/schemas/version'
        appID:
          $ref: '#/components/schemas/identitySat'
        satID:
          $ref: '#/components/schemas/identitySat'
        satSN:
          $ref: '#/components/schemas/serialNumber'
        appCmd:
          $ref: '#/components/schemas/cmd'
        satCmd:
          $ref: '#/components/schemas/cmd'
        holders:
          $ref: '#/components/schemas/holders'
