openapi: 3.0.3
info:
  title: SatAccessToken
  description: API utilizada para gerar arquivos de exemplo através do VSCode
  version: 0.0.1
servers:
  - url: https://api.server.test/v1
paths:
  /api/sat/token-access:
    post:
      summary: Starts OAuth 2.0 authorization and authentication
      description: Starts OAuth 2.0 authorization and authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OAuth2JWEBasic'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/satTokenAccessResponse'
        '400':
          description: 400 | Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: 400 | Bad Request
components:
  schemas:
    OAuth2JWEBasic:
      type: object
      properties:
        grant_type:
          type: string
          enum:
            - client_credentials
          description: Token grant type, must be 'client_credentials' for this flow.
          example: client_credentials
        client_id:
          type: string
          description: Client ID provided by the authorization server.
          example: 1234567890abcdef
        client_secret:
          type: string
          description: Client secret, can be encrypted with JWE.
          example: eyJhbGciOiJFQ0RILUVTIiwiZW5jIjoiQTI1NkNCQy1IUzI1NiJ9.BMBVwxKWsB1CTFgjD0z-FOm90BxaGlYsivOd_1OD8uL-zuKSb9ZVwqriaSkS_3--xRuk5BrRzaIN7GLsLl2FWg0.gTW9vZ6nHpMRFPljOOxSQg.fzxc9QtHgb4rPBSGHoV5hzYWHTQgcO9mlYW2VepGFS8qUG3yF84P-rHFln0sPbe7.LX46hTIU2lce4XJkLJZnj8SN1ZSguaiE-77aZZ5Y6x8
        scope:
          type: string
          description: Space bounded scopes that the client is requesting.
          example: owner
        audience:
          type: string
          description: Token application domain.
          example: https://api.dashcontrol.com
    accessToken:
      type: string
      title: accessToken
      description: The Access Token
      example: eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCIsImp3ayI6eyJrdHkiOiJFQyIsImNydiI6IlAtMjU2IiwieCI6ImtoM3JIbS1xcDhYN3Exdm1qTl9fZGlualJHRTFvcEdKTjFDX1lsTnNvTUEiLCJ5IjoicG1aS1o1ZFo5eEQ3R0ZYYmVCSmNWUnRwVHZVNjROc0h6YmMtQnRHdFE1VSJ9fQ.eyJkYXRhIjoiZXhlbXBsbyBkZSBkb2N1bWVudG8gSlNPTiJ9.hH_3oZKMyDzbYHIEjCJWgGuKOrTwexrX4SJ-hh1njRvoa2cR8wnATt4rLdpj4ApKQt8unIDBukNOQ3_XkpOPPQ
    satTokenAccessResponse:
      type: object
      title: satTokenAccessResponse
      description: 'Schema of Initial Parameters file '
      properties:
        access_token:
          $ref: '#/components/schemas/accessToken'
        token_type:
          type: string
          description: Tipo do token, geralmente 'Bearer'.
          example: Bearer
        expires_in:
          type: integer
          description: Tempo em segundos até a expiração do token.
          example: 3600
